region: us-east-1

function_name: i92_entries
handler: service.handler
role: lambda_api
description: Fetches i92 data, builds a single CSV document, and stores it in S3

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
#aws_access_key_id:
#aws_secret_access_key:

# dist_directory: dist
timeout: 300
memory_size: 128
